### ISSUE TITLE
Javascript not executing properly

### ISSUE THREAD

**Issue by peerbolte** [FWeinb/electron-screenshot-service#23] opened 2016-07-11 13:37 UTC
First off, thank you for creating and maintaining this library. Much appreciated!

I found this library after using nodeshot which I tried on my system and worked. After running this library however I saw that picture rendering didn't seem to work. After some debugging I found out that it was a javascript issue which was the cause of the pictures not loading. 

When I use version 2.3.1 everything works as expected, but 3.0.0 and later do not seem to execute javascript properly. I used the following website to test it: https://www.whatismybrowser.com/detect/is-javascript-enabled 

Maybe some injected javascript is throwing an error which causes the remaining javascript not to execute? I would love to help, but I'm not sure how to debug the electron launched window.  

I'm on OSX 10.11, node v5.2.0

thanks in advance.

**Comment by FWeinb** [comment] 2016-07-12 17:45
Thanks for reporting. There is actually no problem in running javascript. The problem is that jQuery tries to detect the environment and I was beeing stupid in assuming `Object.assing` would be recursive in merging object. It is not. So the [`webPreferences.nodeIntegration`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) was enabled by default. The problem is now fixed in `electron-screenshot-app@3.0.2`. You should be able to reinstall `electron-screenshot-service` and see it working now.

**Closed by FWeinb** 2016-07-12 17:45 UTC
